version: '3.3'

services:

  db:
    restart: always
    container_name: database
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=auctions_db
      - POSTGRES_USER=william
      - POSTGRES_PASSWORD=QWERTY!@#

  redis:
    restart: always
    container_name: 'redis'
    image: redis

  web:
    restart: always
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: auctions
    command: /start
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_worker:
    restart: always
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: worker
    command: /start-celery-worker
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_beat:
    restart: always
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: beat
    command: /start-celery-beat
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
