version: '3.3'

services:
  db:
    container_name: database
    image: postgres
    restart: always

  app:
    container_name: auctions
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
