version: '3.3'

services:

  db:
    restart: always
    container_name: database
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=auctions_db
      - POSTGRES_USER=william
      - POSTGRES_PASSWORD=QWERTY!@#

  web:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=auctions_db
      - POSTGRES_USER=william
      - POSTGRES_PASSWORD=QWERTY!@#
    depends_on:
      - db

  redis:
    restart: always
    container_name: 'celery'
    image: redis
    ports:
      - 6379:6379
