# Generated by Django 4.0.2 on 2022-03-26 17:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('bid_value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ('-bid_value',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01, 'The price must be a positive value.')])),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='auctions/%Y/%m/%d')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField(choices=[(3, 'Three days'), (7, 'One week'), (14, 'Two weeks'), (30, 'One month')])),
                ('ended_manually', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('creation_time',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField(max_length=250)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='auctions.listing')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
