# Generated by Django 4.0.2 on 2022-03-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_category_options_alter_listing_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('-value',)},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bid_value',
            new_name='value',
        ),
    ]
