# Generated by Django 4.0.2 on 2022-04-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creation_time',
            field=models.DateTimeField(),
        ),
    ]
