name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: |
        mkdir .env
        touch ./.env/web_env
        echo DEBUG=${{ secrets.DEBUG }} >> ./.env/web_env
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> ./.env/web_env
        echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> ./.env/web_env
        echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> ./.env/web_env
        echo DB_NAME=${{ secrets.DB_NAME }} >> ./.env/web_env
        echo DB_USER=${{ secrets.DB_USER }} >> ./.env/web_env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> ./.env/web_env
        echo DB_HOST=${{ secrets.DB_HOST }} >> ./.env/web_env
        echo DB_PORT=${{ secrets.DB_PORT }} >> ./.env/web_env
        echo BROKER_URL=${{ secrets.BROKER_URL }} >> ./.env/web_env
        echo CELERY_RESULT_BACKEND=${{ secrets.CELERY_RESULT_BACKEND }} >> ./.env/web_env
        pip3 install -r requirements.txt
        pip3 install --user django
        python3 manage.py test